### ISSUE TITLE
Cannot edit settings

### ISSUE THREAD

**Issue by m0yP** [arafatkn/whmcs-header-footer-injection#1]
I've installed your module a couple of months ago and it worked perfectly, in fact, it still does.

Now, when I wanto to update my meta tags I get the following error in WHMCS: There is no admin output for this module

Any suggestions? Thanks in advance.

**Comment by ghost** [comment]
Which WHMCS version you are using now?

**Comment by m0yP** [comment]
Latest, 8.0.4. I have setup just like instructions say.

**Comment by ghost** [comment]
> Latest, 8.0.4. I have setup just like instructions say.

WHMCS has removed the direct link to the "Addon Modules" page from its top menu. You need to go to "System Settings" first and then go to "Addon Modules".
I will also update the module so that module can be configured more easier.

**Comment by m0yP** [comment]
You are right! Was looking in the wrong place. Thanks for the heads up.
